import { useEffect, useState } from 'react';
import { PageHeader } from '../components/Layout';
import { LocationSelector } from '../components/LocationSelector';
import { AlertList } from '../components/AlertCard';
import { LoadingState, ErrorState } from '../components/common';
import { useApp } from '../context/AppContext';
import { api } from '../services/api';
import type { Alert, AlertSeverity } from '../types';
import clsx from 'clsx';

const SEVERITIES: AlertSeverity[] = ['extreme', 'very_high', 'high', 'moderate', 'low'];

export function AlertsPage() {
  const { location, setLocation, demoMode } = useApp();
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<AlertSeverity | 'all'>('all');
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());

  useEffect(() => {
    setLoading(true);
    const fetch = location
      ? api.getAlerts(location.latitude, location.longitude, demoMode)
      : api.getAlerts(undefined, undefined, true);

    fetch
      .then((d) => setAlerts(d.alerts))
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [location, demoMode]);

  const filtered = alerts
    .filter((a) => !dismissed.has(a.id))
    .filter((a) => filter === 'all' || a.severity === filter);

  const handleDismiss = (id: string) => setDismissed((prev) => new Set([...prev, id]));

  return (
    <div className="space-y-6">
      <PageHeader title="Alerts" subtitle="Early warning alert history and active notifications" />

      {!location && (
        <div className="glass-card p-4">
          <p className="text-sm text-slate-400 mb-3">Select a location for location-specific alerts, or view demo alerts:</p>
          <LocationSelector onSelect={setLocation} />
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => setFilter('all')}
          className={clsx('rounded-full px-3 py-1 text-xs border', filter === 'all' ? 'border-orange-500 text-orange-300' : 'border-slate-600 text-slate-400')}
        >
          All
        </button>
        {SEVERITIES.map((s) => (
          <button
            key={s}
            onClick={() => setFilter(s)}
            className={clsx('rounded-full px-3 py-1 text-xs border capitalize', filter === s ? 'border-orange-500 text-orange-300' : 'border-slate-600 text-slate-400')}
          >
            {s.replace('_', ' ')}
          </button>
        ))}
      </div>

      {loading && <LoadingState />}
      {error && <ErrorState message={error} />}
      {!loading && !error && <AlertList alerts={filtered} onDismiss={handleDismiss} />}

      <p className="text-xs text-slate-500">
        Alerts are generated by HeatGuard AI's alert engine based on modeled predictions. SMS/email notifications are not configured in this prototype.
      </p>
    </div>
  );
}
